Lab3 html/css
SoulHowl/ITandDDP pull request #3
Opened 2022-04-04 09:55 UTC by SoulHowl

Barsukevich S. 953504
Lab3 pull request

2022-04-04 10:20 UTC, katetushkan requested changes
deploy link for html and css?

2022-04-04 11:02 UTC, SoulHowl commented
this should work
https://soulhowl.github.io

2022-04-05 12:13 UTC, katetushkan requested changes

2022-04-05 12:13 UTC, katetushkan commented on Lab3/Weather/index.html
> +                    <h1 class="temperature-1">25&deg;</h1>
U can't use `<h1>` after `<h6>`

2022-04-05 12:13 UTC, katetushkan commented on Lab3/Weather/index.html
> +                <div class="time">
use tag `<time>`

2022-04-05 12:13 UTC, katetushkan commented on Lab3/Weather/index.html
> +                    <h2 class="description">Partly Cloudy</h2>
tags like `<h1..6>` should be used only like headers for page or a section. Don't use them to represent a set of information. Use `<p>`

2022-04-05 12:13 UTC, katetushkan commented on Lab3/Weather/index.html
> +                <div class="numb">
should be `<p>`

2022-04-05 12:13 UTC, katetushkan commented on Lab3/Weather/index.html
> +                <div class="upper-digit"><h3 class="upper-d">18</h3></div>
should be `<p>`

2022-04-05 12:13 UTC, katetushkan commented on Lab3/Weather/Map.html
> +<!DOCTYPE html>
there is no mobile version here (
<img width="689" alt="Screenshot 2022-04-05 at 14 12 19" src="https://user-images.githubusercontent.com/43992068/161751039-6e300bdf-8e81-4453-b627-be39b5ccbdc2.png">
also, smth is wrong with nav 
<img width="686" alt="Screenshot 2022-04-05 at 14 12 43" src="https://user-images.githubusercontent.com/43992068/161751107-6158e332-e22e-4b03-9f5a-c453278b7204.png">

2022-04-07 13:58 UTC, SoulHowl commented
Proj update: fixed small issues, fixed design for phones

2022-04-11 14:27 UTC, katetushkan approved these changes
It's `7`. U OK with that or wanna upgrade?

2022-04-11 15:06 UTC, SoulHowl commented
@katetushkan , it's ok.

2022-04-26 15:08 UTC, merged